export default {
  name: 'praise',
  type: 'document',
  title: 'Praise',
  fields: [
    {
      name: 'date',
      type: 'date',
      description: 'Date of respective service.',
      title: 'Date',
    },
    {
      name: 'lead',
      type: 'string',
      description: 'Worship leader for respective service.',
      title: 'Leader',
    },
    {
      name: 'guitar',
      type: 'string',
      description: 'Guitar player for respective service.',
      title: 'Guitar',
    },
    {
      name: 'keys',
      type: 'string',
      description: 'Keys/Piano player for respective service.',
      title: 'Keys',
    },
    {
      name: 'bass',
      type: 'string',
      description: 'Bass player for respective service.',
      title: 'Bass',
    },
    {
      name: 'drums',
      type: 'string',
      description: 'Drums player for respective service.',
      title: 'Drums',
    },
    {
      name: 'electric',
      type: 'string',
      description: 'Electric Guitar player for respective service.',
      title: 'Electric',
    },
    {
      name: 'backup',
      type: 'string',
      description: 'Backup singers for respective service.',
      title: 'Backup',
    },
    {
      name: 'av',
      type: 'string',
      description: 'Audio/Visual for respective service.',
      title: 'Sound/AV',
    },
    {
      name: 'unavailable',
      type: 'string',
      description: 'Unavailable worship members for respective service.',
      title: 'Unavailable',
    },
    {
      name: 'pdf',
      type: 'file',
      description: 'PDF chords for respective service.',
      title: 'Chords',
    },
    {
      name: 'series',
      type: 'string',
      description: 'Sermon Series for respective service.',
      title: 'Series',
    },
    {
      name: 'topic',
      type: 'string',
      description: 'Sermon Topic for respective service.',
      title: 'Sermon Topic',
    },
    {
      name: 'speaker',
      type: 'string',
      description: 'Speaker/Pastor for respective service.',
      title: 'Speaker',
    },
    {
      name: 'scripture',
      type: 'string',
      description: 'Scripture passage for respective service.',
      title: 'Scripture',
    },
    {
      name: 'objective',
      type: 'string',
      description: 'Sermon objective for respective service.',
      title: 'Objective',
    },
    {
      name: 'summary',
      type: 'string',
      description: 'Sermon sunmary for respective service.',
      title: 'Summary',
    },
  ],
}
