export default {
  name: 'sunday-school',
  type: 'document',
  title: 'Sunday School',
  fields: [
    {
      name: 'class',
      type: 'string',
      title: 'Class',
      description: 'Type of Sunday School class.',
    },
    {
      name: 'lessons',
      type: 'array',
      title: 'Lessons',
      description: 'Lessons (week)',
      of: [
        {
          name: 'lesson',
          type: 'document',
          description: 'Lesson of given worship service.',
          title: 'Lesson',
          fields: [
            {
              name: 'date',
              type: 'date',
              description: 'Date of given lesson.',
              title: 'Date',
            },
            {
              name: 'teacher',
              type: 'string',
              description: 'Teacher for given lesson.',
              title: 'Teacher',
            },
            {
              name: 'assistant',
              type: 'string',
              description: 'Assistant for given lesson.',
              title: 'Assistant',
            },
            {
              name: 'title',
              type: 'string',
              description: 'Title of given lesson.',
              title: 'Lesson Title',
            },
            {
              name: 'objective',
              type: 'string',
              description: 'Objective of given lesson.',
              title: 'Lesson Objective',
            },
            {
              name: 'memoryVerse',
              type: 'string',
              description: 'Memory verse of given lesson.',
              title: 'Memory Verse',
            },
            {
              name: 'biblePassage',
              type: 'url',
              description: 'Bible passage (URL) of given lesson.',
              title: 'Bible Passage',
            },
            {
              name: 'introduction',
              type: 'string',
              description: 'Lesson plan introduction of given lesson.',
              title: 'Lesson Plan Introduction',
            },
            {
              name: 'storytelling',
              type: 'string',
              description: 'Lesson plan storytelling of given lesson.',
              title: 'Lesson Plan Storytelling',
            },
            {
              name: 'discussion',
              type: 'string',
              description: 'Lesson plan discussion of given lesson.',
              title: 'Lesson Plan Discussion',
            },
            {
              name: 'activity',
              type: 'string',
              description: 'Lesson plan activity of given lesson.',
              title: 'Lesson Plan Activity',
            },
            {
              name: 'worksheet',
              type: 'url',
              description: 'Suggested worksheet to print.',
              title: 'Worksheet',
            },
            {
              name: 'craft',
              type: 'url',
              description: 'Suggested craft activity.',
              title: 'Craft',
            },
            {
              name: 'video',
              type: 'url',
              description: 'Suggested video for lesson.',
              title: 'Video',
            },
            {
              name: 'song',
              type: 'url',
              description: 'Suggested action song for lesson.',
              title: 'Action Song',
            },
            {
              name: 'homework',
              type: 'string',
              description: 'Suggested homework for lesson.',
              title: 'Homework',
            },
          ],
        },
      ],
    },
  ],
}
