export const StatementOfFaith = [
	{
		title: '1. God',
		description: 'There is one God, who is infinitely perfect, existing eternally in three persons: Father, Son and Holy Spirit.'
	},
	{
		title: '2. Jesus',
		description: 'Jesus Christ is true God and true man. He was conceived by the Holy Spirit and born of the Virgin Mary. He died upon the cross, the Just for the unjust, as a substitutionary sacrifice, and all who believe in Him are justified on the ground of His shed blood. He arose from the dead according to the Scriptures. He is now at the right hand of the Majesty on high as our great High Priest. He will come again to establish His kingdom of righteousness and peace.'
	},
	{
		title: '3. Holy Spirit',
		description: 'The Holy Spirit is a divine Person, sent to indwell, guide, teach and empower the believer, and to convince the world of sin, of righteousness and of judgment.'
	},
	{
		title: '4. Bible',
		description: "The Old and New Testaments, inerrant as originally given, were verbally inspired by God and are a complete revelation of His will for the salvation of people. They constitute the divine and only rule of Christian faith and practice."
	},
	{
		title: '5. Sin',
		description: 'Humankind, originally created in the image and likeness of God, fell through disobedience, incurring thereby both physical and spiritual death. All people are born with a sinful nature, are separated from the life of God, and can be saved only through the atoning work of the Lord Jesus Christ. The destiny of the impenitent and unbelieving is existence forever in conscious torment, but that of the believer is everlasting joy and bliss.'
	},
	{
		title: '6. Freedom from Sin',
		description: 'Salvation has been provided only through Jesus Christ. Those who repent and believe in Him are united with Christ through the Holy Spirit and are thereby regenerated (born again), justified, sanctified and granted the gift of eternal life as adopted children of God.'
	},
	{
		title: '7. Christian Living',
		description: "It is the will of God that in union with Christ each believer should be sanctified thoroughly thereby being separated from sin and the world and fully dedicated to God, receiving power for holy living and sacrificial and effective service toward the completion of Christ's commission. This is accomplished through being filled with the Holy Spirit which is both a distinct event and progressive experience in the life of the believer."
	},
	{
		title: '8. Healing',
		description: 'Provision is made in the redemptive work of the Lord Jesus Christ for the healing of the mortal body. Prayer for the sick and anointing with oil as taught in the Scriptures are privileges for the Church in this present age.'
	},
	{
		title: '9. Church',
		description: "The universal Church, of which Christ is the Head, consists of all those who believe on the Lord Jesus Christ, are redeemed through His blood, regenerated by the Holy Spirit, and commissioned by Christ to go into all the world as a witness, preaching the Gospel to all nations. The local church, the visible expression of the universal Church, is a body of believers in Christ who are joined together to worship God, to observe the ordinances of Baptism and the Lord's Supper, to pray, to be edified through the Word of God, to fellowship, and to testify in word and deed to the good news of salvation both locally and globally. The local church enters into relationships with other like-minded churches for accountability, encouragement and mission."
	},
	{
		title: '10. Life after death',
		description: 'There shall be a bodily resurrection of the just and of the unjust; for the former, a resurrection unto life; for the latter, a resurrection unto judgment.'
	},
	{
		title: '11. Second Coming of Christ',
		description: "The second coming of the Lord Jesus Christ is imminent and will be personal and visible. As the believer’s blessed hope, this vital truth is an incentive for holy living and sacrificial service toward the completion of Christ's commission."
	}
]